### ISSUE TITLE
showing error in eris logs -  No +2/3 prevotes during enterPrecommit. Precommitting nil

### ISSUE THREAD

**Issue by Akriti-sahu** [monax/hello-doug#14]
Hi,
I have made a chain which has 3 full and 1 root node. The 3 full nodes are connected to each other and showing the eris logs fine. But when I trying to connect the root node to the chain it started and generating blocks also, but in eris logs it showing warning like this -

INFO[01-20|06:45:45] enterPrecommit: No +2/3 prevotes during enterPrecommit. Precommitting nil. module=consensus
INFO[01-20|06:45:45] enterCommit(9171/0). Current: 9171/0/RoundStepPrecommit module=consensus
WARN[01-20|06:45:45] Attempt to finalize failed. We don't have the commit block. module=consensus

I have no idea about what I am doing wrong.
As of my knowledge it needs atleast 2/3rd of votes to pass a transaction. So I have created 3 full nodes that is acting a like a validator also. Sometimes it will generate this above mentioned warning and sometimes it won't. So I need to understand what I am doing wrong here.

Note: I am new to this eris platform and trying to understand the concepts by making own chain locally.

**Comment by zramsay** [comment]
hi @Akriti-sahu can you confirm that your chain is still making blocks? If so, the warning can be safely ignored - they are tendermint warnings rather than actual errors. You should be able to deploy contracts from the root node (please confirm). It's correct that you need > 2/3 validators and note that Root accounts do not have validator permissions.

**Comment by Akriti-sahu** [comment]
@zramsay Thanks for your response.  Yes my root node is still making blocks.  When I am trying to call some methods of my deployed contract in this situation,  it is showing timed out error after some time.  But if this warning doesn't come my deployed contact was working fine. So I thought this might be due to this warning issue.

**Comment by Akriti-sahu** [comment]
Hi, 
I created a new chain with 1:full, 1:root and 2:validators. and it is working fine. I successfully deployed a contract also. Now I am trying to deploy another contract on it using eris pkgs do command but it is neither deploying the contract nor showing any error. only showing this in console:

user1@user1$ eris pkgs do --chain $chainName --address $address
Performing action. This can sometimes take a wee while
Executing Job                                 defaultAddr
user1@user1$ 

## This is my yaml file which I want to deply:
jobs:

- name: deployK1
  job:
    deploy:
      contract: structs2.sol
      instance: Structs2
      wait: true

## **and this is my  structs2.sol file:**
contract Structs2 {
    struct Thing {
        address thingMaker;
        string description;
        string url;
        string filehash;
        string filename;
    }

    Thing[] public things;

    function addThing(string description, string url, string filehash, string filename) returns (uint) {
        things.push(Thing(msg.sender, description, url, filehash, filename));
        return 10;
    }

    function getDesc(uint i) returns(string description) {
        return things[i].description;
    }

    function getUrl(uint i) returns(string url) {
        return things[i].url;
    }

    function getHash(uint i) returns(string filehash) {
        return things[i].filehash;
    }

    function getName(uint i) returns(string filename) {
        return things[i].filename;
    }

}

Is anything I am doing wrong while making the contract? Please help.

eris version - 0.12.0 
Docker version - 1.12.5
Thanks

**Comment by VoR0220** [comment]
Are you executing in same directory of your epm.yaml? Also just a helping hint for the future, you can format and highlight your output with yaml by just writing "yaml" after the three backticks used to format the file.

**Comment by Akriti-sahu** [comment]
@VoR0220 yes,  I am executing eris pkgs do in the same directory where my epm.yaml file is present.

**Comment by VoR0220** [comment]
@Akriti-sahu can you see anything in your job_output.json that would suggest a deployment? If not can you try again and paste the formatted results of the exact same command with a `-d` appended?

**Comment by Akriti-sahu** [comment]
Hi, @VoR0220. Here is my job_output.json file-

{
  "defaultAddr": "5149874569DA23FB2F527C1EFC37B089B4369182"
}

and here is the log of eris pkgs do -d : 

Checking Linux Docker socket                  unix:///var/run/docker.sock
Connecting to Docker                          unix:///var/run/docker.sock
Performing action. This can sometimes take a wee while
                                    host path=/home/user1/.eris/apps/app3
                                          pwd=/home/user1/.eris/apps/app3
No chain flag used. Booting chain from package file
                                              datachain
Starting chain                           name=datachain
Chain definition loaded            chain name=datachain
                                          cmd=
                                   entrypoint=
                                  environment=[]
Booting chain dependencies             chains=[]
                                     services=[]
Starting a chain                              datachain
                              chain container=datachain-0851b948-b5f2-4936-955f-ac1337d018b4
                                  environment=[]
                              ports published=false
Running container                             datachain-0851b948-b5f2-4936-955f-ac1337d018b4
Container already running. Skipping           datachain-0851b948-b5f2-4936-955f-ac1337d018b4
Defaulting to service                 service=struct_app_tmp_
App action built
Getting data container situated           dir=inbound
Loading data definition                       struct_app_tmp_
Creating data container                       struct_app_tmp_-85d184c7-0725-446d-a141-642abd3ed79b
Data container created                        struct_app_tmp_-85d184c7-0725-446d-a141-642abd3ed79b
Setting app data for container           dest=/home/eris/.eris/apps/app3
                                       source=/home/user1/.eris/apps/app3
Importing                                from=/home/user1/.eris/apps/app3
                                           to=/home/eris/.eris/apps/app3
Giving myself all the names                   struct_app_tmp_
Using names                    data container=struct_app_tmp_-85d184c7-0725-446d-a141-642abd3ed79b
                            service container=struct_app_tmp_-85d184c7-0725-446d-a141-642abd3ed79b
Executing data container                      
Loading data definition                       struct_app_tmp_
Executing data container                      struct_app_tmp_-85d184c7-0725-446d-a141-642abd3ed79b
                                         args=[test -d /home/eris/.eris/apps/app3]
Data container configured                 cmd=[test -d /home/eris/.eris/apps/app3]
                                   entrypoint=[]
Data container configured               image=quay.io/eris/data:0.12.0
Executing interactive data container          interactive-23b0933b-b044-425b-a264-29d63e929498
Waiting for container to exit                 interactive-23b0933b-b044-425b-a264-29d63e929498
Removing data container                       interactive-23b0933b-b044-425b-a264-29d63e929498
Data container removed                        interactive-23b0933b-b044-425b-a264-29d63e929498
Directory missing                 destination=/home/eris/.eris/apps/app3
                                        error=Container interactive-23b0933b-b044-425b-a264-29d63e929498 exited with status 1
Running data container                        struct_app_tmp_-85d184c7-0725-446d-a141-642abd3ed79b
                                         args=[/bin/mkdir -p /home/eris/.eris/apps/app3]
Data container configured                 cmd=[/bin/mkdir -p /home/eris/.eris/apps/app3]
                                   entrypoint=[]
Data container configured               image=quay.io/eris/data:0.12.0
Starting data container                       interactive-96677349-bc6b-4e6c-8491-6779167b1d00
Waiting for data container to exit            interactive-96677349-bc6b-4e6c-8491-6779167b1d00
Getting logs from container                   interactive-96677349-bc6b-4e6c-8491-6779167b1d00
Removing data container                       interactive-96677349-bc6b-4e6c-8491-6779167b1d00
Container removed                             interactive-96677349-bc6b-4e6c-8491-6779167b1d00
Importing                                from=/home/user1/.eris/apps/app3
                                           to=/home/eris/.eris/apps/app3
Giving myself all the names                   struct_app_tmp_
Using names                    data container=struct_app_tmp_-85d184c7-0725-446d-a141-642abd3ed79b
                            service container=struct_app_tmp_-85d184c7-0725-446d-a141-642abd3ed79b
Executing data container                      
Loading data definition                       struct_app_tmp_
Executing data container                      struct_app_tmp_-85d184c7-0725-446d-a141-642abd3ed79b
                                         args=[test -d /home/eris/.eris/apps/app3]
Data container configured                 cmd=[test -d /home/eris/.eris/apps/app3]
                                   entrypoint=[]
Data container configured               image=quay.io/eris/data:0.12.0
Executing interactive data container          interactive-c6716910-d4f5-4c4d-a25a-7f037bc3dbaa
Waiting for container to exit                 interactive-c6716910-d4f5-4c4d-a25a-7f037bc3dbaa
Removing data container                       interactive-c6716910-d4f5-4c4d-a25a-7f037bc3dbaa
Data container removed                        interactive-c6716910-d4f5-4c4d-a25a-7f037bc3dbaa
Copying into container                        struct_app_tmp_-85d184c7-0725-446d-a141-642abd3ed79b
                                         path=/home/user1/.eris/apps/app3
Running data container                        struct_app_tmp_-85d184c7-0725-446d-a141-642abd3ed79b
                                         args=[chown --recursive eris /home/eris/.eris/apps/app3]
Data container configured                 cmd=[chown --recursive eris /home/eris/.eris/apps/app3]
                                   entrypoint=[]
Data container configured               image=quay.io/eris/data:0.12.0
Starting data container                       interactive-37f2ead6-9022-4dcd-b6cb-fac136b9e10c
Waiting for data container to exit            interactive-37f2ead6-9022-4dcd-b6cb-fac136b9e10c
Getting logs from container                   interactive-37f2ead6-9022-4dcd-b6cb-fac136b9e10c
Removing data container                       interactive-37f2ead6-9022-4dcd-b6cb-fac136b9e10c
Container removed                             interactive-37f2ead6-9022-4dcd-b6cb-fac136b9e10c
Package path does not exist on the host or is inside the pkg path
PM files do not exist on the host or are inside the pkg path
Starting pkgs action container
                                        image=quay.io/eris/pm:0.12.0
                                      service=struct_app_tmp_
                                   entrypoint=eris-pm --chain tcp://chain:46657 --sign http://keys:4767 --debug  --overwrite  --output json --file epm.yaml --summary  --gas 1111111111 --compiler https://compilers.monax.io:10120 --address 5149874569DA23FB2F527C1EFC37B089B4369182 --fee 1234 --amount 9999
                                        links=[datachain-0851b948-b5f2-4936-955f-ac1337d018b4:chain keys-eb5720b1-8470-4827-82ee-c8ea639e58b7:keys]
                                      workdir=/home/eris/.eris/apps/app3
Executing container                           struct_app_tmp_-4824f826-81ad-48eb-8199-b19f653b04bc
Manage data containers?              autodata=true
Data container already exists, am not creating
Container does not exist. Creating      image=quay.io/eris/pm:0.12.0
Executing interactive container               interactive-d7bc6132-c380-4247-81fe-13777fad9b7e
                                          cmd=[]
                               data container=struct_app_tmp_-85d184c7-0725-446d-a141-642abd3ed79b
                                   entrypoint=[eris-pm --chain tcp://chain:46657 --sign http://keys:4767 --debug --overwrite --output json --file epm.yaml --summary --gas 1111111111 --compiler https://compilers.monax.io:10120 --address 5149874569DA23FB2F527C1EFC37B089B4369182 --fee 1234 --amount 9999]
                                  environment=[]
                                        image=quay.io/eris/pm:0.12.0
                              ports published=false
                                         user=eris
                                         vols=[]
                                      workdir=/home/eris/.eris/apps/app3
Waiting for container to exit                 interactive-d7bc6132-c380-4247-81fe-13777fad9b7e
Removing container                            interactive-d7bc6132-c380-4247-81fe-13777fad9b7e
Container removed                             interactive-d7bc6132-c380-4247-81fe-13777fad9b7e
Hello! I'm EPM.
Using Compiler at                             https://compilers.monax.io:10120
Using Chain at                                tcp://chain:46657
With ChainID                                  
Using Signer at                               http://keys:4767
Using ChainID from Node                       datachain
Loading eris-pm Package Definition File.
Loading eris-pm file                     name=epm
                                         path=/home/eris/.eris/apps/app3
Executing Job                                 defaultAddr
Type                                          Account
Setting Account                               5149874569DA23FB2F527C1EFC37B089B4369182
Getting Public Key                       from=http://keys:4767
calling http://keys:4767/pub
Writing [jobs_output.json] to current directory
Finished performing action
Cleaning up
Getting data container situated           dir=outbound
Loading data definition                       struct_app_tmp_
Setting app data for container           dest=/home/user1/.eris/apps
                                       source=/home/eris/.eris/apps/app3
Exporting data container                      struct_app_tmp_
Giving myself all the names                   struct_app_tmp_
Using names                    data container=struct_app_tmp_-85d184c7-0725-446d-a141-642abd3ed79b
                            service container=struct_app_tmp_-85d184c7-0725-446d-a141-642abd3ed79b
Untarring package from container              /tmp/struct_app_tmp_994272881
Copying out of container                      struct_app_tmp_-85d184c7-0725-446d-a141-642abd3ed79b
                                         path=/home/eris/.eris/apps/app3
Move all files/dirs out of a dir and `rm -rf` that dir
                                         from=/tmp/struct_app_tmp_994272881/.eris
                                           to=/tmp/struct_app_tmp_994272881
No files to move
Removing directory                            /tmp/struct_app_tmp_994272881/.eris
Move all files/dirs out of a dir and `rm -rf` that dir
                                         from=/tmp/struct_app_tmp_994272881
                                           to=/home/user1/.eris/apps
Removing directory                            /tmp/struct_app_tmp_994272881
Package path does not exist on the host or is inside the pkg path
PM files do not exist on the host or are inside the pkg path
Removing data container                       struct_app_tmp_-85d184c7-0725-446d-a141-642abd3ed79b
Removing container                            struct_app_tmp_-85d184c7-0725-446d-a141-642abd3ed79b
Removing data dir on host                 dir=/home/user1/.eris/scratch/data/struct_app_tmp_
user1@user1:~/.eris/apps/app3$

**Comment by Akriti-sahu** [comment]
and one more thing i am facing now is, when I deployed this contract into my chain, that node stops generating blocks also.

**Comment by VoR0220** [comment]
@Akriti-sahu I'm going to ask again, I need this thing formatted...I struggle to read it otherwise...you appear to be new to github so I'll give you this cheat sheet so you can progress faster: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

in addition, from what I can see you put in the wrong command. I need you to put in the exact same command you used to deploy the contract but with the `-d` appended:

```eris pkgs do --chain $chainName --address $address -d``` and from there we'll be able to better figure out the issue. I would also recommend at this point starting the process over:

```
eris clean -y
// restart the tutorial
// document exactly what you put have put in, then come back and show me
```

I really want to help you but in order to do that, I need a better understanding of what it is you are doing and it also helps to have clear differentiators between code/output and text to where you are communicating with me the issue from.

**Comment by Akriti-sahu** [comment]
Hi @VoR0220. Yes I am new to the github, so sorry for the formatting mistakes and thanks for the cheat sheet. As you told, I clean the eris platform in all the systems using-
`eris clean -y`

then I again start my chain that has 1:full, 1:root and 2:validator nodes at each of my 4 systems. I gave the ip of my full node system in the seed value in config.toml file of root node and other 2 validator's node. so that they can connect with the chain.

now my system is up and generating blocks at each node.

then I made a contract structs2.sol -

```
contract Structs2 {
    struct Thing {
        address thingMaker;
        string description;
        string url;
        string filehash;
        string filename;
    }

    Thing[] public things;

    function addThing(string description, string url, string filehash, string filename) returns (uint) {
        things.push(Thing(msg.sender, description, url, filehash, filename));
        return 10;
    }

    function getDesc(uint i) constant returns(string description) {
        return things[i].description;
    }

    function getUrl(uint i) constant returns(string url) {
        return things[i].url;
    }

    function getHash(uint i) constant returns(string filehash) {
        return things[i].filehash;
    }

    function getName(uint i) constant returns(string filename) {
        return things[i].filename;
    }

}
```

and the epm.yaml file for this contract is-
```yaml
jobs:

- name: deployK1
  job:
    deploy:
      contract: structs2.sol
      instance: Structs2
      wait: true
```
then I went into that folder where my epm.yaml file is present and I ran eris pkgs do command to deploy the contract.

`eris pkgs do --chain $chainname --address $address -d`

and got this output-

```
Checking Linux Docker socket                  unix:///var/run/docker.sock
Connecting to Docker                          unix:///var/run/docker.sock
Performing action. This can sometimes take a wee while
                                    host path=/home/user1/.eris/apps/app3
                                          pwd=/home/user1/.eris/apps/app3
No chain flag used. Booting chain from package file
                                              datachain
Starting chain                           name=datachain
Chain definition loaded            chain name=datachain
                                          cmd=
                                   entrypoint=
                                  environment=[]
Booting chain dependencies             chains=[]
                                     services=[]
Starting a chain                              datachain
                              chain container=datachain-8003e865-aa82-44f7-9711-b8bd57c9fa63
                                  environment=[]
                              ports published=false
Running container                             datachain-8003e865-aa82-44f7-9711-b8bd57c9fa63
Container already running. Skipping           datachain-8003e865-aa82-44f7-9711-b8bd57c9fa63
Defaulting to service                 service=struct_app_tmp_
App action built
Getting data container situated           dir=inbound
Loading data definition                       struct_app_tmp_
Creating data container                       struct_app_tmp_-9761ba2b-0c7f-4cfc-8a6b-65b73a3bc0ee
Data container created                        struct_app_tmp_-9761ba2b-0c7f-4cfc-8a6b-65b73a3bc0ee
Setting app data for container           dest=/home/eris/.eris/apps/app3
                                       source=/home/user1/.eris/apps/app3
Importing                                from=/home/user1/.eris/apps/app3
                                           to=/home/eris/.eris/apps/app3
Giving myself all the names                   struct_app_tmp_
Using names                    data container=struct_app_tmp_-9761ba2b-0c7f-4cfc-8a6b-65b73a3bc0ee
                            service container=struct_app_tmp_-9761ba2b-0c7f-4cfc-8a6b-65b73a3bc0ee
Executing data container                      
Loading data definition                       struct_app_tmp_
Executing data container                      struct_app_tmp_-9761ba2b-0c7f-4cfc-8a6b-65b73a3bc0ee
                                         args=[test -d /home/eris/.eris/apps/app3]
Data container configured                 cmd=[test -d /home/eris/.eris/apps/app3]
                                   entrypoint=[]
Data container configured               image=quay.io/eris/data:0.12.0
Executing interactive data container          interactive-956e4635-e3ab-4969-ba7e-0b2367a20b76
Waiting for container to exit                 interactive-956e4635-e3ab-4969-ba7e-0b2367a20b76
Removing data container                       interactive-956e4635-e3ab-4969-ba7e-0b2367a20b76
Data container removed                        interactive-956e4635-e3ab-4969-ba7e-0b2367a20b76
Directory missing                 destination=/home/eris/.eris/apps/app3
                                        error=Container interactive-956e4635-e3ab-4969-ba7e-0b2367a20b76 exited with status 1
Running data container                        struct_app_tmp_-9761ba2b-0c7f-4cfc-8a6b-65b73a3bc0ee
                                         args=[/bin/mkdir -p /home/eris/.eris/apps/app3]
Data container configured                 cmd=[/bin/mkdir -p /home/eris/.eris/apps/app3]
                                   entrypoint=[]
Data container configured               image=quay.io/eris/data:0.12.0
Starting data container                       interactive-36072c92-dbf1-44ca-97dc-55b89d417ae3
Waiting for data container to exit            interactive-36072c92-dbf1-44ca-97dc-55b89d417ae3
Getting logs from container                   interactive-36072c92-dbf1-44ca-97dc-55b89d417ae3
Removing data container                       interactive-36072c92-dbf1-44ca-97dc-55b89d417ae3
Container removed                             interactive-36072c92-dbf1-44ca-97dc-55b89d417ae3
Importing                                from=/home/user1/.eris/apps/app3
                                           to=/home/eris/.eris/apps/app3
Giving myself all the names                   struct_app_tmp_
Using names                    data container=struct_app_tmp_-9761ba2b-0c7f-4cfc-8a6b-65b73a3bc0ee
                            service container=struct_app_tmp_-9761ba2b-0c7f-4cfc-8a6b-65b73a3bc0ee
Executing data container                      
Loading data definition                       struct_app_tmp_
Executing data container                      struct_app_tmp_-9761ba2b-0c7f-4cfc-8a6b-65b73a3bc0ee
                                         args=[test -d /home/eris/.eris/apps/app3]
Data container configured                 cmd=[test -d /home/eris/.eris/apps/app3]
                                   entrypoint=[]
Data container configured               image=quay.io/eris/data:0.12.0
Executing interactive data container          interactive-f7e6e441-e656-4101-83f8-db4fd45c7a77
Waiting for container to exit                 interactive-f7e6e441-e656-4101-83f8-db4fd45c7a77
Removing data container                       interactive-f7e6e441-e656-4101-83f8-db4fd45c7a77
Data container removed                        interactive-f7e6e441-e656-4101-83f8-db4fd45c7a77
Copying into container                        struct_app_tmp_-9761ba2b-0c7f-4cfc-8a6b-65b73a3bc0ee
                                         path=/home/user1/.eris/apps/app3
Running data container                        struct_app_tmp_-9761ba2b-0c7f-4cfc-8a6b-65b73a3bc0ee
                                         args=[chown --recursive eris /home/eris/.eris/apps/app3]
Data container configured                 cmd=[chown --recursive eris /home/eris/.eris/apps/app3]
                                   entrypoint=[]
Data container configured               image=quay.io/eris/data:0.12.0
Starting data container                       interactive-5b50144e-952e-4f5b-a9c3-332cda45300f
Waiting for data container to exit            interactive-5b50144e-952e-4f5b-a9c3-332cda45300f
Getting logs from container                   interactive-5b50144e-952e-4f5b-a9c3-332cda45300f
Removing data container                       interactive-5b50144e-952e-4f5b-a9c3-332cda45300f
Container removed                             interactive-5b50144e-952e-4f5b-a9c3-332cda45300f
Package path does not exist on the host or is inside the pkg path
PM files do not exist on the host or are inside the pkg path
Starting pkgs action container
                                        image=quay.io/eris/pm:0.12.0
                                      service=struct_app_tmp_
                                   entrypoint=eris-pm --chain tcp://chain:46657 --sign http://keys:4767 --debug  --overwrite  --output json --file epm.yaml --summary  --gas 1111111111 --compiler https://compilers.monax.io:10120 --address 5149874569DA23FB2F527C1EFC37B089B4369182 --fee 1234 --amount 9999
                                        links=[datachain-8003e865-aa82-44f7-9711-b8bd57c9fa63:chain keys-72fe20b7-c681-4a7f-942f-552527446526:keys]
                                      workdir=/home/eris/.eris/apps/app3
Executing container                           struct_app_tmp_-2b58da42-4135-4d5d-b737-6ba5c5212cf4
Manage data containers?              autodata=true
Data container already exists, am not creating
Container does not exist. Creating      image=quay.io/eris/pm:0.12.0
Executing interactive container               interactive-3442f1a0-c7b1-416d-b18f-f302145746a0
                                          cmd=[]
                               data container=struct_app_tmp_-9761ba2b-0c7f-4cfc-8a6b-65b73a3bc0ee
                                   entrypoint=[eris-pm --chain tcp://chain:46657 --sign http://keys:4767 --debug --overwrite --output json --file epm.yaml --summary --gas 1111111111 --compiler https://compilers.monax.io:10120 --address 5149874569DA23FB2F527C1EFC37B089B4369182 --fee 1234 --amount 9999]
                                  environment=[]
                                        image=quay.io/eris/pm:0.12.0
                              ports published=false
                                         user=eris
                                         vols=[]
                                      workdir=/home/eris/.eris/apps/app3
Waiting for container to exit                 interactive-3442f1a0-c7b1-416d-b18f-f302145746a0
Removing container                            interactive-3442f1a0-c7b1-416d-b18f-f302145746a0
Container removed                             interactive-3442f1a0-c7b1-416d-b18f-f302145746a0
Hello! I'm EPM.
Using Compiler at                             https://compilers.monax.io:10120
Using Chain at                                tcp://chain:46657
With ChainID                                  
Using Signer at                               http://keys:4767
Using ChainID from Node                       datachain
Loading eris-pm Package Definition File.
Loading eris-pm file                     name=epm
                                         path=/home/eris/.eris/apps/app3
Executing Job                                 defaultAddr
Type                                          Account
Setting Account                               5149874569DA23FB2F527C1EFC37B089B4369182
Getting Public Key                       from=http://keys:4767
calling http://keys:4767/pub
Writing [jobs_output.json] to current directory
Finished performing action
Cleaning up
Getting data container situated           dir=outbound
Loading data definition                       struct_app_tmp_
Setting app data for container           dest=/home/user1/.eris/apps
                                       source=/home/eris/.eris/apps/app3
Exporting data container                      struct_app_tmp_
Giving myself all the names                   struct_app_tmp_
Using names                    data container=struct_app_tmp_-9761ba2b-0c7f-4cfc-8a6b-65b73a3bc0ee
                            service container=struct_app_tmp_-9761ba2b-0c7f-4cfc-8a6b-65b73a3bc0ee
Untarring package from container              /tmp/struct_app_tmp_949814134
Copying out of container                      struct_app_tmp_-9761ba2b-0c7f-4cfc-8a6b-65b73a3bc0ee
                                         path=/home/eris/.eris/apps/app3
Move all files/dirs out of a dir and `rm -rf` that dir
                                         from=/tmp/struct_app_tmp_949814134/.eris
                                           to=/tmp/struct_app_tmp_949814134
No files to move
Removing directory                            /tmp/struct_app_tmp_949814134/.eris
Move all files/dirs out of a dir and `rm -rf` that dir
                                         from=/tmp/struct_app_tmp_949814134
                                           to=/home/user1/.eris/apps
Removing directory                            /tmp/struct_app_tmp_949814134
Package path does not exist on the host or is inside the pkg path
PM files do not exist on the host or are inside the pkg path
Removing data container                       struct_app_tmp_-9761ba2b-0c7f-4cfc-8a6b-65b73a3bc0ee
Removing container                            struct_app_tmp_-9761ba2b-0c7f-4cfc-8a6b-65b73a3bc0ee
Removing data dir on host                 dir=/home/user1/.eris/scratch/data/struct_app_tmp_
user1@user1:~/.eris/apps/app3$ 
```

the jobs_output.json file after executing this is as follows -

`
{
  "defaultAddr": "5149874569DA23FB2F527C1EFC37B089B4369182"
}
`

and the abi folder is not created as I can see that the contract is not deployed successfully in the chain.
I hope now u can understand the things clear. Please help me to find out why my contract is not deploying in the chain. Am I making any wrong solidity file or wrong epm.yaml file??

**Comment by zramsay** [comment]
this is issue for cli: https://github.com/monax/cli ; please open there if still an issue
